---
version: '3.5'

# Create a dedicated network with a domain name
networks:
  siebel:
    name: ${DOMAIN}

secrets:
  keystore:
    file: ./config/keystore.jks
  truststore:
    file: ./config/truststore.jks

#volumes:
  #fs:
  #ai-custom:
  #ai1-config:
  #ai2-config:
  #gateway1-config:
  #gateway1-data:
  #server1-config:

services:

  # Oracle Database
  database:
    image: oracle/database:12.1.0.2-ee
    environment:
      - ORACLE_PWD=oracle12
    volumes:
      - ./data/oradata:/opt/oracle/oradata:z,rw
      - ./scripts/database:/opt/oracle/scripts/setup:z,ro
    networks:
      - siebel
    ports:
      - 1521

  # Siebel Application Interface Server (1st node)
  ai1:
    image: siebel/ai:${SIEBEL_UPDATE}
    hostname: ai1
    domainname: ${DOMAIN}
    networks:
      - siebel
    env_file:
      - ./config/siebel.env
        #volumes:
        #- ai1-config:/siebel/config
        #- ai-custom:/siebel/custom
    secrets:
      - keystore
      - truststore
    ports:
      - 8443

  # Siebel Application Interface Server (1st node)
  ai2:
    image: siebel/ai:${SIEBEL_UPDATE}
    hostname: ai2
    domainname: ${DOMAIN}
    networks:
      - siebel
    env_file:
      - ./config/siebel.env
        #volumes:
        #- ai2-config;/siebel/config
        #- ai-custom:/siebel/custom
    secrets:
      - keystore
      - truststore
    ports:
      - 8443

  # Siebel Gateway (1st node)
  gateway1:
    image: siebel/gateway:${SIEBEL_UPDATE}
    hostname: gateway1
    domainname: ${DOMAIN}
    networks:
      - siebel
    env_file:
      - ./config/siebel.env
    environment:
      - DEPLOY_SCRIPT=/siebel/deploy/deploy.sh
        #volumes:
        #- gateway1-config:/siebel/config
        #- gateway1-data:/siebel/data
    secrets:
      - keystore
      - truststore
    ports:
     - 2320

  # Siebel Server (1st node)
  server1:
    image: siebel/server:${SIEBEL_UPDATE}
    hostname: server1
    domainname: ${DOMAIN}
    networks:
      - siebel
    env_file:
      - ./config/siebel.env
        #    volumes:
        #- server1-config:/siebel/config
        #- fs:/siebel/fs
    secrets:
      - keystore
      - truststore
    ports:
     - 2320
