---
version: '3.5'

# Create a dedicated network with a domain name
networks:
  siebel:
    name: ${DOMAIN}

secrets:
  keystore:
    file: ./config/keystore.jks
  truststore:
    file: ./config/truststore.jks

services:

  # Oracle Database
  database:
    image: oracle/database:12.1.0.2-ee
    environment:
      - ORACLE_PWD=oracle12
    volumes:
      - ./data/oradata:/opt/oracle/oradata
      - ./scripts/database:/opt/oracle/scripts/setup
    networks:
      - siebel
    ports:
      - 1521

  # Siebel Application Interface Server #1
  ai1:
    image: siebel/ai:${SIEBEL_UPDATE}
    hostname: ai1
    domainname: ${DOMAIN}
    networks:
      - siebel
    env_file:
      - ./config/siebel.env
    secrets:
      - keystore
      - truststore
    ports:
      - 8443
